-- MySQL Script generated by MySQL Workbench
-- Sun Jul 14 18:54:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema foroconnet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema foroconnet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `foroconnet` DEFAULT CHARACTER SET utf8 ;
USE `foroconnet` ;

-- -----------------------------------------------------
-- Table `foroconnet`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroconnet`.`curso` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `categoria` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `foroconnet`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroconnet`.`usuario` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `correoElectronico` VARCHAR(250) NOT NULL,
  `contrasena` VARCHAR(250) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `perfiles` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `foroconnet`.`topico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroconnet`.`topico` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `mensaje` VARCHAR(250) NOT NULL,
  `fechaCreacion` VARCHAR(250) GENERATED ALWAYS AS () VIRTUAL,
  `status` VARCHAR(250) NOT NULL,
  `autor` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL,
  `curso` VARCHAR(250) NOT NULL,
  `respuestas` VARCHAR(250) GENERATED ALWAYS AS (),
  `id_curso` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_curso_idx` (`id_curso` ASC) VISIBLE,
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `id_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `foroconnet`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `foroconnet`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `foroconnet`.`respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroconnet`.`respuesta` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `id` INT NOT NULL,
  `mensaje` VARCHAR(250) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `topico` VARCHAR(250) NOT NULL,
  `fechaCreacion` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `solucion` VARCHAR(250) NOT NULL,
  `id_topico` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_topico_idx` (`id_topico` ASC) VISIBLE,
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `id_topico`
    FOREIGN KEY (`id_topico`)
    REFERENCES `foroconnet`.`topico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `foroconnet`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `foroconnet`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroconnet`.`perfil` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroconnet`.`perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroconnet`.`perfiles` (
  `usuario_id` INT NOT NULL,
  `perfil_id` INT NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_has_perfil_perfil1_idx` (`perfil_id` ASC) VISIBLE,
  INDEX `fk_usuario_has_perfil_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_perfil_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `foroconnet`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_perfil_perfil1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `foroconnet`.`perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
